### ISSUE TITLE
does it get occluded behind objects?

### ISSUE THREAD

**Issue by laurentopia** [ColinLeung-NiloCat/UnityURP-BillboardLensFlareShader#2]
i see you reference INSIDE which does occlusion by sampling depth on 4 corners
I don't see any occlusion so I'm wondering if perhaps it's not implemented or my settings are off?
![image](https://user-images.githubusercontent.com/26075468/92292877-5aad3680-eed4-11ea-8c96-fe06b64109c1.png)

**Comment by ColinLeung-NiloCat** [comment]
did you enable URP's depth texture?

**Comment by laurentopia** [comment]
I hadn't - now it works, thanks
