### ISSUE TITLE
UV Problem with clip optimization

### ISSUE THREAD

**Issue by yeongjo** [ColinLeung-NiloCat/UnityURP-BillboardLensFlareShader#3]
![https://i.ibb.co/frwT1bp/shaderbug.gif](https://i.ibb.co/frwT1bp/shaderbug.gif)
https://i.ibb.co/frwT1bp/shaderbug.gif

https://github.com/ColinLeung-NiloCat/UnityURP-BillboardLensFlareShader/blob/1defbb6e392b18ad37a1994a89a46cbbc30a2c24/URP_NiloCatExtension_BillboardLensFlare.shader#L225

When i use pure optimization that clip pos move far away (Genius!!)
Quad uv become screen space uv ;(
It's happen only Unity Editor on gles32

Are you didn't have problem with android devices?

**Comment by ColinLeung-NiloCat** [comment]
did you mean unity editor(platform switched to android)?

**Comment by ColinLeung-NiloCat** [comment]
I tested on Android<DX11>, but I didn't build opengle3.x test on mobile

**Comment by ColinLeung-NiloCat** [comment]
It should be fixed in the current version, if this bug still exists, please upload a new issue, thank you!
