### ISSUE TITLE
Material with Shader doesn't have a texture property _MainTex

### ISSUE THREAD

**Issue by Kadae** [ColinLeung-NiloCat/UnityURP-BillboardLensFlareShader#5]
This shader works perfectly, but when object is active this errors loops in Console in Edit Mode...

I'm added `_MainTex("Main Texture", 2D) = "**SHADER_NAME**" {}` to the Shader for the quick fix. Works for me.

**Comment by ColinLeung-NiloCat** [comment]
It should be fixed in the current version, if this bug still exists, please upload a new issue, thank you!
