### ISSUE TITLE
Unity 2021.1.6

### ISSUE THREAD

**Issue by CosmicStud** [ColinLeung-NiloCat/UnityURP-BillboardLensFlareShader#6]
Some changes in URP, breaks functionality

**Comment by ColinLeung-NiloCat** [comment]
We tested this shader on 
-2020.3.30f1(URP 10.8.1)
-2021.2.16f1(URP 12.1.6)
it is working correctly(Android/Standalone/WebGL).

Make sure depth texture is enabled, if the shader is not working, please start a new issue, thank you!
