### ISSUE TITLE
Not working on URP 10.5.1 and 11.0.0

### ISSUE THREAD

**Issue by Snail921** [ColinLeung-NiloCat/UnityURP-BillboardLensFlareShader#7]
Almost same as issue #6 but anyway I confirmed the shader struggles working properly on URP 10.5.1 and 11.0.0.

**Comment by antigollos** [comment]
Agree, tested URP 10.5.1 with Unity 2020.3.14f1 which is the latest 2020.x LTS version. Unity is changing URP logic every two weeks. :/

**Comment by ColinLeung-NiloCat** [comment]
We tested this shader on 
-2020.3.30f1(URP 10.8.1)
-2021.2.16f1(URP 12.1.6)
it is working correctly(Android/Standalone/WebGL).

Make sure depth texture is enabled, if the shader is not working, please start a new issue, thank you!
